version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /c/Exatip/Tutorials/DockerTutorial/db/mongo_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: emp
  mongo-express:
    container_name: mongo-express-db
    image: mongo-express
    restart: always
    ports:
      - 8081:8081     
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: emp    
  springboot-mongodb-employee-cont:
    container_name: springboot-mongodb-employee-cont
    image: springboot-mongodb-employee-app
    restart: always
    ports:
      - 4041:4040
    environment:
      MONGO_DATABASE: emp
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: emp
      SPRINGBOOT_APP_PORT: 4040

# /c/Exatip/Tutorials/DockerTutorial/db/mongo_db is local host m/c path      